version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports: 
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data 
  pg-admin:
    image: dpage/pgadmin4:6
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com 
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: '../server'
    container_name: api_server
    volumes:
      - /app/node_modules
      - ../server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    ports:
    - '4000:4000'
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ../client
    container_name: client
    volumes:
      - /app/node_modules
      - ../client:/app
    ports:
      - '3000:3000'
  customer:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ../customer-client
    container_name: customer_client
    volumes:
      - /app/node_modules
      - ../customer-client:/app
    ports:
      - '3001:3001'

volumes:
  data:
          