version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports: 
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data 
  pg-admin:
    image: dpage/pgadmin4:6
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com 
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: '../server'
    volumes:
      - /app/node_modules
      - ../server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
    ports:
    - '4000:4000'
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ../client
    volumes:
      - /app/node_modules
      - ../client:/app

volumes:
  data:
          